### ISSUE TITLE
Extend Supported platforms to OpenGL ES 3 to Universal Windows Platform?

### ISSUE THREAD

**Issue by JimSEOW** [ka-decimu/old_engine#1]
Current supported platforms

Direct3D 11 / Windows Desktop
OpenGL ES 3 / Windows Desktop via PowerVR SDK
Direct3D 11 / Windows Phone 8.1 / Universal Windows Platform
OpenGL ES 3 / Linux X11

WIth https://github.com/Microsoft/angle, perhaps fgEngine could support OpenGL ES 3 for UWP

**Comment by ka-decimu** [comment]
But why? Engine uses actual implementation of PlatformInterface. In UWP case is native D3D11. Native platform, without wrappers, is more performant.
